### PR TITLE
1.18 inital port

### PR DESCRIPTION
**Pull request by imreallybadatnames**
note: block entity rendering is broken(blocks render, everything else doesnt)﻿

### CODE REVIEW

**Comment by imreallybadatnames** [comment]
rendering issue was from desync(server doesnt send packets to client about block entity update)
will commit the fix to pr soon

**Comment by imreallybadatnames** [comment]
should be all good now

**Comment by imreallybadatnames** [comment]
cloth config is also required for this mod so including it in dependencies

**Comment by imreallybadatnames** [comment]
not so initial now

**Comment by imreallybadatnames** [comment]
a lot of tags are wrong so its initial port

**Comment by imreallybadatnames** [comment]
yeah i cant fix it.
i dont have the magical abilities to conditionally add smelting recipes if the ingot tag exists.

**Comment by imreallybadatnames** [comment]
well it works now

**Comment by LordDeatHunter** [comment]
I almost didn't see this, thanks for helping out! It would be great if you could also contact me on discord:
DH#9367

**Pull request merged**
